### ISSUE TITLE
Can't load offline

### ISSUE THREAD

**Issue by lowburger** [CompSciOrBust/Amiigo#10]
Hi,

You could make offline mode for the homebrew? I know we won't able to use all feature. For now forever stuck on waiting for internet connection screen. Thx!

**Comment by CompSciOrBust** [comment]
I haven't decided yet but for now you can download this json file and place it in sdmc:/config/amiigo/API.json

https://amiiboapi.com/api/amiibo/

**Comment by CompSciOrBust** [comment]
Closing because 2.1.0 embeds a copy of the API cache
