### ISSUE TITLE
Add amiiboseries to list of amiibos

### ISSUE THREAD

**Issue by hahnmt** [CompSciOrBust/Amiigo#11]
The current amiibo maker list groups the amiibo by Game Series. This is great, except certain amiibo overlap between games, such as the Zelda amiibo, which exists in LOZ amiibo series, and SSBU amiibo series. 

If amiiboseries could be added to the list view, it would be easy to distinguish Zelda SSBU from Zelda LOZ. 

Currently two Zelda appear on the list.

Alternatively, change the sort method to amiibo series rather than game series.

**Comment by CompSciOrBust** [comment]
I don't actually use Amiibos that much so I'm not sure what the difference is between game series and Amiibo series. I'm open to changing the behavior but could you explain the difference between the two so I know why it would make Amiigo better?

**Comment by hahnmt** [comment]
Sure. This is just one person's opinion. 

The emutool designed with the emuiibo product uses amiiboseries groups also. 

I see the rationale like this - when searching for an amiibo I don't look first for what game franchise the character is from, I look for the amiibo series that matches the game I am playing. 


For example 
- When playing SSBU, I want to use my SSBU amiibos. the SSBU amiibos offer certain benefits that match the SSBU game
- BOTW game - if I use the Zelda amiibo from SSBU the game rewards are bows. If I use the Zelda from the TLOZ amiibo series, the rewards are shields. If I want to make the choice, I would pick which amiibo series the Zelda is from. 

I found it semi-confusing when I was looking for amiibos that were released specifically for BOTW game when I was playing this week.  I could not distinguish the smash amiibos from the BOTW amiibo series.

Thanks for responding

**Comment by CompSciOrBust** [comment]
Alright, I don't have time to work on Amiigo currently so I'll add a toggle to my todo list for when I do have time. For now here's a quick and dirty edit to make it sort by amiiboSeries. Untested so let me know if it has issues.
[Amiigo.zip](https://github.com/CompSciOrBust/Amiigo/files/7534749/Amiigo.zip)

**Comment by CompSciOrBust** [comment]
Added a toggle and made Amiigo Maker sort by Amiibo series. Will release soon.

**Comment by CompSciOrBust** [comment]
Added in 2.2.0 https://github.com/CompSciOrBust/Amiigo/releases/tag/2.2.0
