### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yyoossk** [CompSciOrBust/Amiigo#12]
C:/Users/hiroki2/Amiigo/Arriba/include/arribaGraphics.h:3:10: fatal error: glad/glad.h: No such file or directory
    3 | #include <glad/glad.h>

**Comment by CompSciOrBust** [comment]
sudo dkp-pacman -S switch-glad

You also need switch-glm

**Comment by CompSciOrBust** [comment]
Added better build instructions. https://github.com/CompSciOrBust/Amiigo#building
