### ISSUE TITLE
emuiibo favorites integration?

### ISSUE THREAD

**Issue by monstrosities** [CompSciOrBust/Amiigo#16]
Hi there,

Thanks for the cool homebrew, I've been using it lately to swap amiibo especially in games where multiple are used since tesla can be quite unstable.

One thing that would be a really nice addition for the above would be to read and write to emuiibo overlay's favorites file and use it for a favorites menu in amiigo, that would really speed things up when swapping amiibo instead of having to go through several directories. Would you consider working that in?

It's a plaintext file stored at `sd:/emuiibo/overlay/favorites.txt`

Example of favorites.txt contents:
```
sdmc:/emuiibo/amiibo/Animal Crossing/Cyrus
sdmc:/emuiibo/amiibo/Chibi-Robo!/Chibi Robo
sdmc:/emuiibo/amiibo/Legend of Zelda/Bokoblin
sdmc:/emuiibo/amiibo/Legend of Zelda/Daruk
sdmc:/emuiibo/amiibo/Monster Hunter Stories/Ena
```

**Comment by CompSciOrBust** [comment]
I'm going to be busy for the next week but I'll see if I can add it in the next release along with a fix for the dock resolution bug

**Comment by monstrosities** [comment]
Cool thank you!

**Comment by CompSciOrBust** [comment]
Do you have Discord? I installed Tesla to get a feel for how the favorites file should work but I can't get the overlay to recognize the entries as Amiibos. It keeps opening them as if they were directories. If I could talk to you over Discord I could probably get the feature added faster.

**Comment by CompSciOrBust** [comment]
I spoke with XorTroll. The issue was how newlines are encoded and parsed by the overlay.

**Comment by CompSciOrBust** [comment]
Added in e8b1367ed6eee3592fffef7db2f790031ee3f262. Will probably release tomorrow.

**Comment by monstrosities** [comment]
Excellent!! Many thanks for that!
