### ISSUE TITLE
Error installing on Firmware 15.0.0

### ISSUE THREAD

**Issue by ReflexReaction** [CompSciOrBust/Amiigo#17]
As per screen, crashes Atmosphere when installing.

FW 15.0.0
Atmosphere 1.4.0

![image](https://user-images.githubusercontent.com/72594363/222395748-0530c796-4397-42b7-a86c-bcf35a258198.jpg)

**Comment by CompSciOrBust** [comment]
Does it work if you delete the /config/Amiigo folder on your SD Card?

**Comment by CompSciOrBust** [comment]
Closing as it seems to work fine for me on latest firmware + Atmosphere version
