### ISSUE TITLE
Very slow to start

### ISSUE THREAD

**Issue by frax1988** [CompSciOrBust/Amiigo#18]
I wanted to update my database so i booted up the app with wifi on, but ever since it has been very slow to boot up the app. Before it was almost instant, now it will take 1-2 minutes before starting. Is there any way to resolve this?

**Comment by frax1988** [comment]
A comp

**Comment by frax1988** [comment]
Woops accidently closed it, didn't want to wanted to post an update. A reboot seemed to have fixed the slow Amiigo boot issue but now i can't seem to get it to work. Before i could use it in airplanemode, now i can't use it in either airplane mode or connected to wifi.

**Comment by CompSciOrBust** [comment]
What happens when you open it now? Does it just crash? Try deleting /config/Amiigo/API.json and then booting the app in airplane mode

**Comment by frax1988** [comment]
The app tells me the amiibo has been loaded but when i return to my game to 'scan' it, it doesn't work. No crashes and i have tried different amiibo's. Will try your solution tomorrow!

**Comment by CompSciOrBust** [comment]
For some games (like BoTW) you have to select at least 1 Amiibo with Amiigo before launching the game for it to work correctly. Try that too (close the game from the Switch home screen, select an Amiibo, then launch the game again. After that you can Switch Amiibos in Amiigo freely).

**Comment by frax1988** [comment]
Not sure what worked, did a couple of things. The above however did not work for me immediately. I copied a 'fresh' copy of the nro file, then booted amiigo first -> game but didn't pick it up. But after i went back into amiigo disabled and enabled emuiibo (X button twice) and selected another one it was working? I don't really understand how this fixed it but i guess i can't complain since it's working again. Guess i'll close it for now, not sure how to reproduce this so i can give a definitive answer what the fix actually was. 

Thanks for replying though and helping me (and meaby others) out.

**Comment by CompSciOrBust** [comment]
No problem. I have a long list of bugs that need fixed once I repair my Switch.
