### ISSUE TITLE
Atmosphère 0.10.1 FW 9.1.0 incompatibility

### ISSUE THREAD

**Issue by smegster** [CompSciOrBust/Amiigo#2]
I've tried both 1.5.1 and 1.5.2 and neither work on Atmosphère 0.10.1 FW 9.1.0

1.5.1 doesn't let me select any any amiibo on the list tab.
1.5.2 just black screens which forces me to use the home button to exit.

**Comment by CompSciOrBust** [comment]
That's weird. It definitely supports Atmosphere 0.10.1 so it must be fw 9.1.0 that breaks it as far as I can tell. I'll update my switch when I have some free time to try to fix it. Thanks for letting me know.

**Comment by CompSciOrBust** [comment]
I updated to fw 9.1.0 and it works fine for me. Do you definitely have Emuiibo installed? Some users seem to be confused about what Amiigo does. Amiigo interfaces with Emuiibo by XorTroll and makes it possible to generate virtual Amiibos on the Switch which isn't possible with Emuiibo alone.
https://github.com/XorTroll/emuiibo

**Comment by smegster** [comment]
It looks like Emuiibo may have been causing the black screen. I downloaded from the App Store which seemed to fix the opening issue. The problem I have now is that when I try to download the amiibos none of them appear in the amiibo list. 

At first I thought it might be down to permissions so I opened the home brew channel using the game + r method and still no joy.

**Comment by smegster** [comment]
I've managed to solve the issue and its all working now. It looks like the folder may have been created using my Mac which I've had issues with before. When I created the Amiigo folder on my pc it worked perfectly. Adding for Mac users who may suffer similar issues.

**Comment by CompSciOrBust** [comment]
Sorry I didn't see your previous comment. I'll pin this in case other mac users also have this issue. It's probably the archive bit. I'll look in to setting / unsetting the archive bit automatically for the next release.
