### ISSUE TITLE
Update to emuiibo 0.5

### ISSUE THREAD

**Issue by impeeza** [CompSciOrBust/Amiigo#8]
Hi, Emuiibo 0.5 was released and works a lot different.  thanks a lot for your hard work

**Comment by CompSciOrBust** [comment]
The new IPC is almost entirely different so it would take a lot of work to get it functioning with 0.5.0. I want to update it but my Switch has hardware failure so until I can get a new one my Switch projects are dead. Sorry. I'll leave this issue open so other people can see.

**Comment by impeeza** [comment]
Sorry to hear about that.  Regards from Colombia

**Comment by CompSciOrBust** [comment]
Fixed in f64f84856a0e3bfc9c3e7318d8dbd71c8b7fa5ba

**Comment by impeeza** [comment]
Thanks a lot buddy
