### ISSUE TITLE
Amiigo isnt working with the Neutos fork of Atomosphere

### ISSUE THREAD

**Issue by subhyde** [CompSciOrBust/Amiigo#9]
When booting Amiigo, The yellow "Emuiibo not loaded"  is present on the bottom of the screen. everything is up to date, reinstalling amiigo/emuiibo multiple times does not solve the issue.

running os 9.2.0
neutos version: 0.12.0

**Comment by CompSciOrBust** [comment]
What version of Emuiibo are you using? 0.5.0 changed lots of IPC stuff breaking compatibility with Amiigo and I can't update it because my Switch is hard bricked. If it doesn't work using Emuiibo 0.4.x then it's probably an incompatibility between Neutos and Emuiibo.

**Comment by CompSciOrBust** [comment]
Closing because Neutos was discontinued.
